language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
script:
- npm run check
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: sadorlovsky@gmail.com
  skip_cleanup: true
  api_key:
    secure: AM7Twp7UB5J1NHfv8rzw1uQrhhx/OmC3HInjXd9RBtAL7+RTZcw5A53jKjyhaPMBhj8kSB7ZegbAOz9vHMw5fEfmJvcdAp6/OXJXwgJdaGexZZnXtDiTyCtwGSpFBA4ytuplQ+lT3tOxcuk/FXmMqUuOPqHWM4NAWtHk60LOcR2WuEhOD0pa1SbNBzfoOv4ay4z+o8RtVKcqIz5f1U9/ofZSWk0Gd2u65EhVO+wDYS7jIxMWkedn6iIQvKRLeSDjL9EcWB3mOkRJZt0fuk4pzZ8IOpkvheT7wNAMGrfLY0SGFJZVcTrYhyxLXFu+CtXwUvPegVAi3kuiz7wSfMvJf8y8rVxxsY1/v1rqQMhQsTdn4tQDeIyf9weao7BBuWGZaiBtfdb75S1MXDrO1ZSTiRWUm3Lo06hxFxDo8q7AVV/RYjYa0MWcVr2aMPxTT0W2jvjXYGyR/4aGXU6MiS0dqt8Fk8vlAssIk+RGW7nQG6v4bKrEsRLNS24OTgXErc1KLIkSHDbvQltFSARCKpbxFHTRLAgyu8uCNDP50kcoNuk7Yz9jgJ6ipbadMA+HKoX6OIqKucu401vNkIQIlby8ip0ChiyFmtENIHHhkoKU7KtGlA6RNW6PktLvyqnI5Lva8OVeGf3h0ztZ5SdjYEy2p2JrH1rbPx3twqy090qBoqU=
  on:
    tags: true
    repo: sadorlovsky/dockerps
    node: '4'
